CREATE TABLE IF NOT EXISTS jobs(
    id SERIAL PRIMARY KEY,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	name VARCHAR(70) NOT NULL,
	email VARCHAR(120) NOT NULL,
	password VARCHAR(255) NOT NULL
);

