CREATE TABLE IF NOT EXIST jobs(
    id SERIAL PRIMARY KEY,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXIST users(
	id SERIAL PRIMARY KEY,
	name VARCHAR(70) NOT NULL,
	email VARCHAR(120) NOT NULL,
	password VARCHAR(255) NOT NULL
);

